name: maikago
description: "まいカゴ – 値札読み取りで買い物の合計金額が一瞬でわかる"
publish_to: 'none'
version: 1.1.4+49
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  cloud_functions: ^6.0.1
  google_sign_in: ^7.1.1
  http: ^1.1.0
  provider: ^6.0.5
  google_fonts: ^6.3.1
  in_app_purchase: ^3.2.3
  in_app_purchase_android: ^0.4.0+4
  in_app_purchase_storekit: ^0.4.0+3
  package_info_plus: ^9.0.0
  google_mobile_ads: ^6.0.0
  uuid: ^4.3.3
  image_picker: ^1.0.4
  camera: ^0.11.2
  shared_preferences: ^2.2.0
  url_launcher: ^6.2.5
  image: ^4.1.7
  permission_handler: ^12.0.1
  crypto: ^3.0.3
  cupertino_icons: ^1.0.2
  webview_flutter: ^4.13.0
  webview_flutter_android: ^4.10.2
  webview_flutter_wkwebview: ^3.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  mockito: ^5.5.1
  build_runner: ^2.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/launcher_icon/
    - assets/ai_jp/
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icon/icon.jpg"
  min_sdk_android: 21
  adaptive_icon_padding: true
  web:
    generate: true
    image_path: "assets/launcher_icon/icon.jpg"
    background_color: "#ffffff"
    theme_color: "#000000"
  windows:
    generate: true
    image_path: "assets/launcher_icon/icon.jpg"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/launcher_icon/icon.jpg"
